# Technical Notes
---
## How to Store Vegetables Without Plastic
- **Artichokes**: place in an airtight container sealed, with light moisture.
- **Asparagus**: place them loosely in a glass or bowl upright with water at room temperature. (Will keep for a week outside the fridge)
- Avocados‐ place in a paper bag at room temp. To speed up their ripening‐ place an apple in the bag with them.
- Arugula‐ arugula, like lettuce, should not stay wet! Dunk in cold water and spin or lay flat to dry. Place dry arugula in an open container, wrapped with a dry towel to absorb any extra moisture.
- Basil‐ is difficult to store well. Basil does not like the cold, or to be wet for that matter. The best method here is an airtight container/jar loosely packed with a small damp piece of paper inside‐left out on a cool counter.
- Beans, shelling‐ open container in the fridge, eat ASAP. Some recommend freezing them if not going to eat right away
- Beets‐ cut the tops off to keep beets firm, (be sure to keep the greens!)by leaving any top on root vegetables draws moisture from the root, making them loose flavor and firmness. Beets should be washed and kept in and open container with a wet towel on top.
- Beet greens‐ place in an airtight container with a little moisture.
- Broccoli‐ place in an open container in the fridge or wrap in a damp towel before placing in the fridge.
- Broccoli Rabe‐ left in an open container in the crisper, but best used as soon as possible.
- Brussels Sprouts‐ If bought on the stalk leave them on that stalk. Put the stalk in the fridge or leave it on a cold place. If they’re bought loose store them in an open container with a damp towel on top.
- Cabbage‐ left out on a cool counter is fine up to a week, in the crisper otherwise. Peel off outer leaves if they start to wilt. Cabbage might begin to loose its moisture after a week , so, best used as soon as possible.
- Carrots‐ cut the tops off to keep them fresh longer. Place them in closed container with plenty of moisture, either wrapped in a damp towel or dunk them in cold water every couple of days if they’re stored that long.
- Cauliflower‐ will last a while in a closed container in the fridge, but they say cauliflower has the best flavor the day it’s bought.
- Celery‐ does best when simply places in a cup or bowl of shallow water on the counter.
- Celery root/Celeriac‐ wrap the root in a damp towel and place in the crisper.
- Corn‐ leave unhusked in an open container if you must, but corn really is best eaten sooner then later for maximum flavor.
- Cucumber‐ wrapped in a moist towel in the fridge. If you’re planning on eating them within a day or two after buying them they should be fine left out in a cool room.
- Eggplant‐ does fine left out in a cool room. Don’t wash it, eggplant doesn’t like any extra moisture around its leaves. For longer storage‐ place loose, in the crisper.
- Fava beans‐ place in an air tight container.
- Fennel‐ if used within a couple days after it’s bought fennel can be left out on the counter, upright in a cup or bowl of water (like celery). If wanting to keep longer than a few days place in the fridge in a closed container with a little water.
- Garlic‐ store in a cool, dark, place.
- Green garlic‐an airtight container in the fridge or left out for a day or two is fine, best before dried out.
- Greens‐ remove any bands, twist ties, etc. most greens must be kept in an air‐tight container with a damp cloth‐ to keep them from drying out. Kale, collards, and chard even do well in a cup of water on the counter or fridge.
- Green beans‐ they like humidity, but not wetness. A damp cloth draped over an open or loosely closed container.
- Green Tomatoes‐ store in a cool room away from the sun to keep them green and use quickly or they will begin to color.
- Herbs- a closed container in the fridge to kept up to a week. Any longer might encourage mold.
- Lettuce‐ keep damp in an airtight container in the fridge.
- Leeks‐leave in an open container in the crisper wrapped in a damp cloth or in a shallow cup of water on the counter (just so the very bottom of the stem has water).
- Okra‐ doesn’t like humidity. So a dry towel in an airtight container. Doesn’t store that well, best eaten quickly after purchase
- Onion‐ store in a cool, dark and dry, place‐ good air circulation is best, so don’t stack them.
- Parsnips‐an open container in the crisper, or, like a carrot, wrapped in a damp cloth in the fridge.
- Potatoes‐ (like garlic and onions) store in cool, dark and dry place, such as, a box in a dark corner of the pantry; a paper bag also works well.
- Radicchio‐ place in the fridge in an open container with a damp cloth on top.
- Radishes‐ remove the greens (store separately) so they don’t draw out excess moisture from the roots and place them in a open container in the fridge with a wet towel placed on top.
- Rhubarb‐wrap in a damp towel and place in an open container in the refrigerator.
- Rutabagas‐ in an ideal situation a cool, dark, humid root cellar or a closed container in the crisper to keep their moisture in.
- Snap peas‐ refrigerate in an open container
- Spinach‐ store loose in an open container in the crisper, cool as soon as possible. Spinach loves to stay cold.
- Spring onions‐ Remove any band or tie and place in the crisper.
- Summer Squash‐ does fine for a few days if left out on a cool counter, even after cut.
- Sweet peppers‐ Only wash them right before you plan on eating them as wetness decreases storage time. Store in a cool room to use in a couple a days, place in the crisper if longer storage needed.
- Sweet Potatoes‐ Store in a cool, dark, well‐ventilated place. Never refrigerate‐‐sweet potatoes don’t like the cold.
- Tomatoes‐ Never refrigerate. Depending on ripeness, tomatoes can stay for up to two weeks on the counter. To hasten ripeness place in a paper bag with an apple.
- Turnips‐ remove the greens (store separately) same as radishes and beets, store them in an open container with a moist cloth.
- Winter squash‐store in a cool, dark, well ventilated place. Many growers say winter squashes get sweeter if they’re stored for a week or so before eaten.
- Zucchini‐ does fine for a few days if left out on a cool counter, even after cut. Wrap in a cloth and refrigerate for longer storage.
- How To Store Fruit Without Plastic
- Apples: store on a cool counter or shelf for up to two weeks. For longer storage in a cardboard box in the fridge.
- Citrus: store in a cool place, with good airflow, never in an air‐tight container.
- Apricots‐ on a cool counter to room temperature or fridge if fully ripe
- Cherries‐store in an airtight container. Don’t wash cherries until ready to eat, any added moisture encourages mold.
- Berries-Don’t forget, they’re fragile. When storing be careful not to stack too many high, a single layer if possible. A paper bag works well, only wash before you plan on eating them.
- Dates‐dryer dates (like Deglet Noor) are fine stored out on the counter in a bowl or the paper bag they were bought in. Moist dates (like Medjool) need a bit of refrigeration if they’re going to be stored over a week, either in cloth or a paper bag‐ as long as it’s porous to keeping the moisture away from the skin of the dates.
- Figs‐ Don’t like humidity, so, no closed containers. A paper bag works to absorb excess moisture, but a plate works best in the fridge up to a week un‐stacked.
- Melons‐ uncut in a cool dry place, out of the sun up to a couple weeks. Cut melons should be in the fridge, an open container is fine.
- Nectarines‐ (similar to apricots) store in the fridge is okay if ripe, but best taken out a day or two before you plan on eating them so they soften to room temperature.
- Peaches (and most stone fruit)‐ refrigerate only when fully ripe. More firm fruit will ripen on the counter.
- Pears‐ will keep for a few weeks on a cool counter, but fine in a paper bag. To hasten the ripening put an apple in with them.
- Persimmon –Fuyu‐(shorter/pumpkin shaped): store at room temperature.–Hachiya‐ (longer/pointed end): room temperature until completely mushy. The astringentness of them only subsides when they are completely ripe. To hasten the ripening process place in a paper bag with a few apples for a week, check now and then, but don’t stack‐they get very fragile when really ripe.
- Pomegranates‐ keep up to a month stored on a cool counter.
- Strawberries‐ Don’t like to be wet. Do best in a paper bag in the fridge for up to a week. Check the bag for moisture every other day.

## References
1. https://www.washingtonsgreengrocer.com/everything-else/storage-tips May 4, 2015
2. http://www.specialtybottle.com/glassbottles-2.aspx
